# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Default Sofle Keymap'
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Submodules
        run: |
          git config --global --add safe.directory '*'
          make git-submodule
      - name: Build Default Sofle Keymap
        run: qmk compile -kb sofle/rev1 -km default
      - name: Copy firmware
        run: |
          mkdir -p artifacts
          cp *sofle_rev1_default* artifacts/ || true
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sofle-rev1-default-firmware
          path: artifacts
        continue-on-error: true
